server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: profiles-service
          uri: lb://profiles-service
          predicates:
            - Path=/api/v1/profiles/**
        - id: iam-microservice
          uri: lb://iam-microservice
          predicates:
            - Path=/api/v1/accounts/**
            - Path=/api/v1/authentication/**
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/subscriptions/**
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/v1/menu/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/v1/orders/**
